spring.application.name=DriverService

server.port=8083

#Remote postgress connection - neon
spring.datasource.url=jdbc:postgresql://ep-small-haze-ait2utky-pooler.c-4.us-east-1.aws.neon.tech/cabbie_db1?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_sjlGu3bCP2DZ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= RETRY =================
resilience4j.retry.instances.userService.maxAttempts=4
resilience4j.retry.instances.userService.waitDuration=1s
resilience4j.retry.instances.userService.retryExceptions=feign.RetryableException,feign.FeignException,java.io.IOException,java.net.ConnectException
resilience4j.retry.retryAspectOrder=2

# ================= CIRCUIT BREAKER =================
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1

# ===================Kafka ==========================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=driver-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
# Required when producer uses spring.json.add.type.headers=false (no type in headers).
spring.kafka.consumer.properties.spring.json.value.default.type=com.cabbie.driver.dto.RideRequestedEvent

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.properties.spring.json.trusted.packages=*
