spring.application.name=DriverService

server.port=8083

#Remote postgress connection - neon
spring.datasource.url=jdbc:postgresql://ep-small-haze-ait2utky-pooler.c-4.us-east-1.aws.neon.tech/cabbie_db1?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_sjlGu3bCP2DZ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= RETRY =================
resilience4j.retry.instances.userService.maxAttempts=4
resilience4j.retry.instances.userService.waitDuration=1s
resilience4j.retry.instances.userService.retryExceptions=feign.RetryableException,feign.FeignException,java.io.IOException,java.net.ConnectException
resilience4j.retry.retryAspectOrder=2

# ================= CIRCUIT BREAKER =================
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
