spring.application.name=Userprofile

server.port=8081

#Mysql connection

spring.datasource.url=jdbc:mysql://localhost:3306/cabbie_db1?serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=****

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

