server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: driver-service
          uri: lb://DRIVERSERVICE
          predicates:
            - Path=/driver/**

        - id: ride-service
          uri: lb://RIDESERVICE
          predicates:
            - Path=/rides/**
  application:
    name: APIGateway

jwt:
  secret: mySecretKeyForJwtValidation123456


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/